strictness: medium
test-warnings: false
doc-warnings: false
member-warnings: true
ignore-paths:
  - scripts

pyroma:
  run: true

pylint:
  options:
    max-args: 8
    max-attributes: 12
  disable:
    - useless-suppression

pyflakes:
  disable:
    - F401 # unused import, covered by pylint
