language: python

python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'

install:
  - pip install -e .
  - pip install -r requirements_dev.txt
  - '[[ $TRAVIS_PYTHON_VERSION != 3* ]] && pip install mock'

script:
  - py.test
  - pylint --rcfile=.pylintrc -f text -r n --confidence=HIGH,INFERENCE,INFERENCE_FAILURE allib

sudo: false
