language: python

python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install -e .
  - pip install -r requirements_dev.txt
  - 'if [[ $TRAVIS_PYTHON_VERSION = 2* ]]; then pip install mock; fi'

script:
  - py.test
  - pylint -E allib

sudo: false
